version: '3.8'

services:
  nextjs:
    build:
      context: ./hmftweb
    container_name: hmftweb-nextjs-app
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./hmftweb:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: hmftweb-postgres-db
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: hmftweb-adminer
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      - db

volumes:
  db_data: