version: '3.8'

services:
  #Production
  # Untuk produksi, gunakan build dari Dockerfile
  hmftweb-production:
    build:
      context: ./hmftweb
      dockerfile: Dockerfile
    container_name: hmftweb-production
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: true
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "${PROD_PORT}:3000"
    
    
  #Development
  # Untuk development, gunakan volume untuk sinkronisasi kode
  hmftweb-development:
    build:
      context: ./hmftweb
    container_name: hmftweb-development
    restart: always
    ports:
      - "${DEV_PORT}:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./hmftweb:/app
    depends_on:
      - db


  #Database
  # Gunakan PostgreSQL sebagai database
  db:
    image: postgres:15
    container_name: hmftweb-postgres-db
    restart: always
    environment:
      POSTGRES_DB: hmftdb
      POSTGRES_USER: hmftuser
      POSTGRES_PASSWORD: hmftpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"


  #Adminer
  # Gunakan Adminer untuk manajemen database
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db

volumes:
  db_data: